config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("project_app.urls")),
    path("admin/", admin.site.urls),
    path("bot/", include("django_telegram.urls", namespace="bot")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

nublado/apps/django_telegram/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import BotWebhookView

app_name = "django_telegram"

urlpatterns = [
    path(
        "<bot_id>/webhook/",
        csrf_exempt(BotWebhookView.as_view()),
        name="bot_webhook_view",
    ),
]

nublado/apps/project_app/urls.py
from django.urls import path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from .views import HomeView, HealthView

app_name = "project_app"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("health", HealthView.as_view(), name="health"),
    # path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')))
]

nublado/apps/django_telegram/models.py
from telegram.constants import ChatType, ChatMemberStatus

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from django_nublado_core.models import TimestampModel, LanguageModel
from .managers import (
    TelegramUserManager,
    TelegramChatManager,
    TelegramGroupMemberManager,
)


class TelegramUser(TimestampModel):
    """
    Model for a Telegram user.
    """

    telegram_id = models.BigIntegerField(primary_key=True)

    username = models.CharField(max_length=255, null=True, blank=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    is_bot = models.BooleanField(default=False)

    objects = TelegramUserManager()

    def __str__(self):
        # In case username doesn't exist, just return the id.
        return self.username or str(self.telegram_id)


class TelegramChat(TimestampModel):
    """
    Model for a Telegram chat
    """

    class ChatType(models.TextChoices):
        PRIVATE = ChatType.PRIVATE, _("private")
        GROUP = ChatType.GROUP, _("group")
        SUPERGROUP = ChatType.SUPERGROUP, _("supergroup")
        CHANNEL = ChatType.CHANNEL, _("channel")

    telegram_id = models.BigIntegerField(primary_key=True)

    # These fields are "snapshots" of their respective values derived from Telegram.
    chat_type = models.CharField(max_length=20, choices=ChatType)
    title = models.CharField(max_length=255, null=True, blank=True)
    username = models.CharField(max_length=255, null=True, blank=True)

    objects = TelegramChatManager()

    def __str__(self):
        return f"{self.telegram_id}: {self.title}: {self.chat_type}"


class TelegramGroupSettings(LanguageModel, TimestampModel):
    chat = models.OneToOneField(
        TelegramChat,
        on_delete=models.CASCADE,
        related_name="settings",
    )

    def __str__(self):
        return f"Settings: {self.chat} (language={self.language})"


class TelegramGroupMember(TimestampModel):
    """
    Model for a member of a Telegram group.
    """

    class GroupRole(models.TextChoices):
        MEMBER = ChatMemberStatus.MEMBER, _("member")
        ADMIN = ChatMemberStatus.ADMINISTRATOR, _("admin")
        OWNER = ChatMemberStatus.OWNER, _("owner")

    user = models.ForeignKey(
        TelegramUser,
        on_delete=models.CASCADE,
        related_name="memberships",
    )
    chat = models.ForeignKey(
        TelegramChat,
        on_delete=models.CASCADE,
        related_name="members",
    )

    # This is just a "snapshot" of the group member's role. Don't
    # use it for permissions. Rather, use the role data from Telegram
    # that this field is derived from.
    role = models.CharField(max_length=20, choices=GroupRole)

    is_active = models.BooleanField(default=True)
    joined_at = models.DateTimeField(auto_now_add=True)
    left_at = models.DateTimeField(null=True, blank=True)

    # Optional for group "karma points." This can be extracted to its own
    # table if more elaborate point features are needed.
    points = models.IntegerField(default=0)

    objects = TelegramGroupMemberManager()

    class Meta:
        unique_together = ("user", "chat")
        indexes = [
            models.Index(fields=["chat", "-points"]),
        ]

    def __str__(self):
        return f"{self.user} in {self.chat} ({self.role})"

nublado/apps/users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.urls import reverse
from django.db import models
from django.utils.translation import gettext_lazy as _

from django_nublado_core.models import TimestampModel, UUIDModel
from .managers import UserManager


class User(UUIDModel, TimestampModel, PermissionsMixin, AbstractBaseUser):
    username = models.CharField(
        verbose_name=_("label_username"),
        max_length=50,
        unique=True,
    )
    email = models.EmailField(
        verbose_name=_("label_email"),
        max_length=50,
        unique=True,
    )
    first_name = models.CharField(
        verbose_name=_("label_first_name"),
        max_length=100,
    )
    last_name = models.CharField(
        verbose_name=_("label_last_name"),
        max_length=100,
    )
    is_active = models.BooleanField(verbose_name=_("label_is_active"), default=False)
    is_admin = models.BooleanField(verbose_name=_("label_is_admin"), default=False)

    objects = UserManager()
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = [
        "email",
    ]

    def __str__(self):
        return "{0} : {1}".format(self.email, self.get_full_name())

    def clean(self, *args, **kwargs):
        self.email = self.email.lower()
        self.username = self.username.lower()

    @property
    def is_staff(self):
        return self.is_admin

    def get_full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

nublado/apps/django_telegram/views.py
import json
import logging

from telegram import Update

from django.http import Http404, JsonResponse
from django.views import View
from django.conf import settings

from .bot_registry import registry


class BotWebhookView(View):
    async def post(self, request, *args, **kwargs):
        bot_id = kwargs["bot_id"]
        if bot_id in settings.BOTS:
            await registry.ensure_initialized(bot_id)

            app = registry.get(bot_id)

            try:
                data = json.loads(request.body.decode("utf-8"))
            except Exception as e:
                logger.error(f"Error in decoding update: {e}")
                raise Http404
            try:
                update = Update.de_json(data, app.bot)
                await app.process_update(update)
                return JsonResponse({"ok": True})
            except Exception as e:
                logger.error(f"Error in processing update: {e}")
                raise Http404
        else:
            raise Http404

nublado/apps/project_app/views.py
from django.views.generic import View, TemplateView
from django.http import JsonResponse


class HomeView(TemplateView):
    template_name = "home.html"


class HealthView(View):

    def get(self, request, *args, **kwargs):
        return JsonResponse({"message": "OK"}, status=200)

nublado/apps/project_app/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

<html lang="en">

<head>

<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
{% block title %}{% endblock title %} | {{ project_name }}
</title>

<link rel="icon" href="{% static 'favicon.ico' %}">

{% block stylesheets %}

<link rel="stylesheet" href="{% static 'css/app.css' %}" />
<link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}" />

{% endblock stylesheets %}

{% block styles %}
{% endblock styles %}

</head>

<body class="{% block body_classes %}sidebar-animated{% endblock body_classes %}" style="min-height: 100vh;">

<div id="app-container">

{% block navbar %}

<nav class="navbar is-bordered" role="navigation" aria-label="main navigation">

<div class="navbar-brand">

<a 
role="button" 
class="navbar-sidebar-trigger" 
aria-label="navbar-sidebar-trigger" 
@click.prevent="toggleSidebar"
>
<span></span>
<span></span>
<span></span>
</a>

<a class="navbar-item" href="{% url 'project_app:home' %}">
<img src="{% static 'images/nublado-logo.png' %}" alt="nublado-logo">
</a>

</div>

<div 
id="navbar-menu" 
class="navbar-menu"
ref="navbarMenu"
>

<div class="navbar-end">

<a class="navbar-item">
Login
</a>

</div><!-- navbar-end -->

</div><!-- navbar-menu -->

</nav>

{% endblock navbar %}

{% block sidebar %}

<!-- sidebar -->
<div id="sidebar-overlay" class="sidebar-overlay" @click="toggleSidebar(false)"></div>

<div
id="sidebar"
class="sidebar"
ref="sidebar"
>
<div class="sidebar-container">

<div class="sidebar-navbar">

<a 
role="button" 
class="navbar-sidebar-trigger" 
aria-label="sidebar-trigger" 
@click.prevent="toggleSidebar"
>
<span></span>
<span></span>
<span></span>
</a>

<a class="navbar-item" href="{% url 'project_app:home' %}">
<img src="{% static 'images/nublado-logo.png' %}" alt="nublado-logo">
</a>

</div><!-- sidebar-navbar -->

<div class="sidebar-body">

{% block sidebar_nav_items %}

<div class="menu">

<p class="menu-label">
General
</p>

<ul class="menu-list">
<li>
<a href="{% url 'project_app:home' %}" ><i class="fas fa-fw fa-home menu-icon"></i> Home</a>
</li>
<li>
<a><i class="fas fa-fw fa-language menu-icon"></i> Settings</a>
</li>
</ul>

</div>

{% endblock sidebar_nav_items %}

</div><!--sidebar-body -->

<div class="sidebar-footer">
</div>

</div><!-- sidebar-container -->
</div><!-- sidebar -->

{% endblock sidebar %}


{% block hero_section %}
{% endblock hero_section %}

</div><!-- app-container -->

{% block scripts %}
<script>
var sidebarExpanded = false;
</script>

<script src="{% static 'js/vue3.js' %}"></script>
<script src="{% static 'js/vue/app.js' %}"></script>

{% endblock scripts %}

</body>
</html>

nublado/apps/project_app/templates/home.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Home" %}{% endblock title %}

{% block hero_section %}
<section class="parallax-hero">

<div class="hero-body">

<div class="title is-size-1">{% trans "Django async prototype." %}</div>
<div class="subtitle is-size-3">{% trans "Testing testing 123..." %}</div>

</div>

</section>
{% endblock hero_section %}

nublado/apps/project_app/templates/includes/_messages.html
{% if messages %}

  {% for message in messages %}
    <alert-message 
    {% if message.tags %} message-type="{{ message.tags }}" {% endif %} 
    message-text="{{ message }}"
    :init-auto-close="true"
    >
    </alert-message>
  {% endfor %}

{% endif %}

nublado/apps/project_app/templates/includes/_modal.html
{% load core_extras %}

{% if not modal_id %}{% alias 'modal' as modal_id %}{% endif %}

{% if not modal_name %}{% alias 'modal' as modal_name %}{% endif %}

{% if not modal_trigger %}{% alias 'showModal' as modal_trigger %}{% endif %}

<{{ modal_name }} 
{% block modal_extra %}{% endblock modal_extra %} 
v-cloak 
inline-template
init-id="{{ modal_id }}"
>

<transition name="fade-transition" v-on:after-enter="isOpen = true" v-on:after-leave="isOpen = false">

<div 
id="{{ modal_id }}"
class="modal {% block modal_classes %}{% endblock modal_classes %}"
v-bind:class="[{ 'is-active': isOpen }]"
@click.stop
>

<div class="modal-background" @click="close"></div>

<div class="modal-content">
<div class="box">

{% block modal_content %}

<header class="modal-header">

{% block modal_header %}{% endblock modal_header %}

</header>

<section class="modal-body">

{% block modal_body %}{% endblock modal_body %}

</section>

<footer class="modal-footer">

{% block modal_footer %}{% endblock modal_footer %}

</footer>

{% endblock modal_content %}

</div>
</div>

</div>

</transition>

</{{ modal_name }}>

nublado/apps/project_app/templates/includes/_user_nav.html
{% load core_extras %}
{% load profile_image_tags %}
{% load i18n %}

{% if not user.is_authenticated %}

  <a href="{% url_set_param 'security:login' next=request.path %}" class="navbar-item login-link">
  {% trans "label_login" %}
  </a>

{% else %}

  <navbar-dropdown 
  id="navbar-user-dropdown"
  dropdown-classes="user-menu"
  >

  <template slot="dropdown-label">
    {% profile_image user 40 'circle' %}
  </template>

  <template slot="dropdown-content">

  {% block navbar_menu_items %}

    <div class="navbar-item">
    <span class="user-nav-avatar">
    {% profile_image user 40 "circle" %}
    </span>
    <span class="navbar-username" style="margin-left: 10px;">{{ user.username }}</span>
    </div>

    <hr class="navbar-divider">

    <a class="navbar-item" href="{% url 'users:profile_update' user.username %}">
    <span class="user-menu-icon">
    <i class="fas fa-edit fa-fw"></i>
    </span>
    {% trans "label_edit_profile" %}
    </a>

    <hr class="navbar-divider">

    <a class="navbar-item logout-link" href="{% url 'security:logout' %}">
    <span class="user-menu-icon">
    <i class="fas fa-sign-out-alt fa-fw"></i>
    </span>
    {% trans "label_logout" %}
    </a>
  {% endblock navbar_menu_items %}

  </template>

  </navbar-dropdown>

{% endif %}